# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\"\x1e\n\x0eSummaryRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"!\n\x0fSummaryResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2;\n\tAIService\x12.\n\tSummarize\x12\x0f.SummaryRequest\x1a\x10.SummaryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARYREQUEST']._serialized_start=12
  _globals['_SUMMARYREQUEST']._serialized_end=42
  _globals['_SUMMARYRESPONSE']._serialized_start=44
  _globals['_SUMMARYRESPONSE']._serialized_end=77
  _globals['_AISERVICE']._serialized_start=79
  _globals['_AISERVICE']._serialized_end=138
# @@protoc_insertion_point(module_scope)
